# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/suggestions/suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/suggestions/suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/suggestions/suggestions.proto\x12\x0bsuggestions\"Z\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x34\n\norder_data\x18\x02 \x01(\x0b\x32 .suggestions.SuggestionOrderData\"2\n\x11InitOrderResponse\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\"=\n\x13SuggestionOrderData\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rordered_items\x18\x02 \x03(\t\"\xa0\x01\n\x11SuggestionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x45\n\x0cvector_clock\x18\x02 \x03(\x0b\x32/.suggestions.SuggestionRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xb8\x01\n\x12SuggestionResponse\x12&\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x11.suggestions.Book\x12\x46\n\x0cvector_clock\x18\x02 \x03(\x0b\x32\x30.suggestions.SuggestionResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"6\n\x04\x42ook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2\xb3\x01\n\x12SuggestionsService\x12J\n\tInitOrder\x12\x1d.suggestions.InitOrderRequest\x1a\x1e.suggestions.InitOrderResponse\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.suggestions.suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUGGESTIONREQUEST_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_SUGGESTIONREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_INITORDERREQUEST']._serialized_start=55
  _globals['_INITORDERREQUEST']._serialized_end=145
  _globals['_INITORDERRESPONSE']._serialized_start=147
  _globals['_INITORDERRESPONSE']._serialized_end=197
  _globals['_SUGGESTIONORDERDATA']._serialized_start=199
  _globals['_SUGGESTIONORDERDATA']._serialized_end=260
  _globals['_SUGGESTIONREQUEST']._serialized_start=263
  _globals['_SUGGESTIONREQUEST']._serialized_end=423
  _globals['_SUGGESTIONREQUEST_VECTORCLOCKENTRY']._serialized_start=373
  _globals['_SUGGESTIONREQUEST_VECTORCLOCKENTRY']._serialized_end=423
  _globals['_SUGGESTIONRESPONSE']._serialized_start=426
  _globals['_SUGGESTIONRESPONSE']._serialized_end=610
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_start=373
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_end=423
  _globals['_BOOK']._serialized_start=612
  _globals['_BOOK']._serialized_end=666
  _globals['_SUGGESTIONSSERVICE']._serialized_start=669
  _globals['_SUGGESTIONSSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
