services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      - orchestrator

  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
    depends_on:
      - fraud_detection
      - transaction_verification
      - suggestions
      - order_queue

  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src

  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src

  suggestions:
    build:
      context: ./
      dockerfile: ./suggestions/Dockerfile
    ports:
      - 50053:50053
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/suggestions/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./suggestions/src:/app/suggestions/src

  order_queue:
    build:
      context: ./
      dockerfile: ./order_queue/Dockerfile
    ports:
      - 50054:50054
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_queue/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./order_queue/src:/app/order_queue/src

  order_executor_1:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    ports:
      - 50055:50055
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
      - PYTHONPATH=/app
      - EXECUTOR_ID=1
      - EXECUTOR_NAME=order_executor_1
      - EXECUTOR_PORT=50055
      - ORDER_QUEUE_ADDRESS=order_queue:50054
      - BOOKS_DATABASE_ADDRESS=books_database_1:50057
      - EXECUTOR_PEERS=1@order_executor_1:50055,2@order_executor_2:50055
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue
      - books_database_1
      - books_database_2
      - books_database_3

  order_executor_2:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    ports:
      - 50056:50055
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
      - PYTHONPATH=/app
      - EXECUTOR_ID=2
      - EXECUTOR_NAME=order_executor_2
      - EXECUTOR_PORT=50055
      - ORDER_QUEUE_ADDRESS=order_queue:50054
      - BOOKS_DATABASE_ADDRESS=books_database_1:50057
      - EXECUTOR_PEERS=1@order_executor_1:50055,2@order_executor_2:50055
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue
      - books_database_1
      - books_database_2
      - books_database_3

  books_database_1:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    ports:
      - 50057:50057
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database/src/app.py
      - PYTHONPATH=/app
      - DATABASE_PORT=50057
      - ROLE=head
      - NEXT_HOST=books_database_2
      - HEAD_ADDRESS=books_database_1:50057
      - TAIL_ADDRESS=books_database_3:50057
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src

  books_database_2:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    ports:
      - 50058:50057
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database/src/app.py
      - PYTHONPATH=/app
      - DATABASE_PORT=50057
      - ROLE=middle
      - NEXT_HOST=books_database_3
      - HEAD_ADDRESS=books_database_1:50057
      - TAIL_ADDRESS=books_database_3:50057
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
    depends_on:
      - books_database_1

  books_database_3:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    ports:
      - 50059:50057
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database/src/app.py
      - PYTHONPATH=/app
      - DATABASE_PORT=50057
      - ROLE=tail
      - HEAD_ADDRESS=books_database_1:50057
      - TAIL_ADDRESS=books_database_3:50057
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
    depends_on:
      - books_database_2

  payment:
    build:
      context: ./
      dockerfile: ./payment/Dockerfile
    ports:
      - 50060:50060
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/payment/src/app.py
      - PYTHONPATH=/app
      - PAYMENT_PORT=50060
      # bonus point: payment prepares OK, but times out on first commit attempt.
      - PAYMENT_COMMIT_SLEEP_SECONDS=10
      - PAYMENT_COMMIT_SLEEP_PROBABILITY=0.5
    volumes:
      - ./utils:/app/utils
      - ./payment/src:/app/payment/src