# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\x85\x02\n\x0c\x46raudRequest\x12\x30\n\x0b\x63redit_card\x18\x01 \x01(\x0b\x32\x1b.fraud_detection.CreditCard\x12$\n\x05items\x18\x02 \x03(\x0b\x32\x15.fraud_detection.Item\x12\x31\n\x0f\x62illing_address\x18\x03 \x01(\x0b\x32\x18.fraud_detection.Address\x12\'\n\x06\x64\x65vice\x18\x04 \x01(\x0b\x32\x17.fraud_detection.Device\x12)\n\x07\x62rowser\x18\x05 \x01(\x0b\x32\x18.fraud_detection.Browser\x12\x16\n\x0eterms_accepted\x18\x06 \x01(\x08\"B\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"(\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\"\"\n\x06\x44\x65vice\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02os\x18\x02 \x01(\t\"\x17\n\x07\x42rowser\x12\x0c\n\x04name\x18\x01 \x01(\t\"F\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x0f\n\x07reasons\x18\x03 \x03(\t2d\n\x15\x46raudDetectionService\x12K\n\nCheckFraud\x12\x1d.fraud_detection.FraudRequest\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDREQUEST']._serialized_start=43
  _globals['_FRAUDREQUEST']._serialized_end=304
  _globals['_CREDITCARD']._serialized_start=306
  _globals['_CREDITCARD']._serialized_end=372
  _globals['_ITEM']._serialized_start=374
  _globals['_ITEM']._serialized_end=412
  _globals['_ADDRESS']._serialized_start=414
  _globals['_ADDRESS']._serialized_end=454
  _globals['_DEVICE']._serialized_start=456
  _globals['_DEVICE']._serialized_end=490
  _globals['_BROWSER']._serialized_start=492
  _globals['_BROWSER']._serialized_end=515
  _globals['_FRAUDRESPONSE']._serialized_start=517
  _globals['_FRAUDRESPONSE']._serialized_end=587
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=589
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
