# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/order_executor/order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\x12\x0eorder_executor\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\'\n\x12\x43oordinatorRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"!\n\x13\x43oordinatorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\r\n\x0bPingRequest\"\x1a\n\x0cPingResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x80\x02\n\x14OrderExecutorService\x12M\n\x08\x45lection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12V\n\x0b\x43oordinator\x12\".order_executor.CoordinatorRequest\x1a#.order_executor.CoordinatorResponse\x12\x41\n\x04Ping\x12\x1b.order_executor.PingRequest\x1a\x1c.order_executor.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=64
  _globals['_ELECTIONREQUEST']._serialized_end=103
  _globals['_ELECTIONRESPONSE']._serialized_start=105
  _globals['_ELECTIONRESPONSE']._serialized_end=135
  _globals['_COORDINATORREQUEST']._serialized_start=137
  _globals['_COORDINATORREQUEST']._serialized_end=176
  _globals['_COORDINATORRESPONSE']._serialized_start=178
  _globals['_COORDINATORRESPONSE']._serialized_end=211
  _globals['_PINGREQUEST']._serialized_start=213
  _globals['_PINGREQUEST']._serialized_end=226
  _globals['_PINGRESPONSE']._serialized_start=228
  _globals['_PINGRESPONSE']._serialized_end=254
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=257
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
